/**
 * AquaPi Swagger API
 * REST API for the AquaPi
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Feeder } from './feeder';
import { Lamp } from './lamp';
import { LightSensor } from './lightSensor';
import { Pump } from './pump';
import { Thermometer } from './thermometer';
import { WaterFlowSensor } from './waterFlowSensor';
import { WaterLevelSensor } from './waterLevelSensor';


/**
 * Data structure that holds information about all used components. Also holds the Pi Id and a timestamp.
 */
export interface ComponentSettings {
    piid?: string;

    timestamp?: Date;

    waterflowsensor?: WaterFlowSensor;

    lightsensor?: LightSensor;

    waterlevelsensor?: WaterLevelSensor;

    thermometer?: Thermometer;

    lamp?: Lamp;

    feeder?: Feeder;

    pump?: Pump;

}
