/**
 * AquaPi Swagger API
 * REST API for the AquaPi
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Fishes {
    piid?: string;

    fishid?: string;

    name?: string;

    quantity?: number;

    mintemp?: number;

    maxtemp?: number;

    frostfood?: number;

    flakefood?: number;

    livefood?: number;

    needshiding?: number;

    helplink?: string;

    piclink?: string;

    minquantity?: number;

    weight?: number;

}
