/**
 * AquaPi Swagger API
 * REST API for the AquaPi
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface MessagesMessages {
    type?: MessagesMessages.TypeEnum;

    message?: string;

}
export namespace MessagesMessages {
    export enum TypeEnum {
        Error = <any> 'error',
        Warning = <any> 'warning',
        Info = <any> 'info',
        Suggestion = <any> 'suggestion'
    }
}
